services:

  api-rtrainers:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bot_rtrainers
    ports:
      - '8501:8501'
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=localhost
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data